export const AUTHOR_FIRSTNAME = 'Faith';
export const AUTHOR_LASTNAME = 'Pellas';
export const AUTHOR_FULLNAME = `${AUTHOR_FIRSTNAME} ${AUTHOR_LASTNAME}`;
export const BASE_PATH = `https://raw.githubusercontent.com/fbpellas/fbpellas.github.io/main/public/`;
export const BASE_PATH_IMG = `${BASE_PATH}img/`;
export const BASE_PATH_SOUNDS = `${BASE_PATH}sounds/`;
export const CREATION_YEAR_START = 2020;
export const CREATION_YEAR_END = 2022;
export const EMAIL = 'fbpellas@usfca.edu';
