export const diphthongs = [
  [
    "/aɪ/",
    "i, igh, y, ie",
    "<u>i</u>ce, b<u>ye</u>, l<u>i</u>me, f<u>igh</u>t, sk<u>y</u>",
    "diphthongs/phonemes/-aɪ-.m4a",
    "diphthongs/examples/ice, bye, lime, fight , sky.m4a",
  ],
  [
    "/eɪ/",
    "a, a-e, ai, ay, eigh, ey",
    "<u>a</u>corn, j<u>a</u>de, p<u>ai</u>d, w<u>eigh</u>t, h<u>ey</u>",
    "diphthongs/phonemes/-eɪ-.m4a",
    "diphthongs/examples/acorn, jade, paid, weight, hey.m4a",
  ],
  [
    "/ɔɪ/",
    "oi, oy",
    "b<u>oy</u>, c<u>oi</u>n, s<u>oi</u>l, v<u>oi</u>ce, turqu<u>oi</u>se",
    "diphthongs/phonemes/-ɔɪ-.m4a",
    "diphthongs/examples/boy, coin, soil, voice, turquoise.m4a",
  ],
  [
    "/oʊ/",
    "o, ow",
    "g<u>o</u>, t<u>o</u>tal, gr<u>ow</u>, <u>o</u>ver, g<u>ol</u>d",
    "diphthongs/phonemes/-oʊ-.m4a",
    "diphthongs/examples/go, total, grow, over, gold.m4a",
  ],
  [
    "/aʊ/",
    "ow",
    "c<u>ow</u>, n<u>ow</u>, br<u>ow</u>n, w<u>ow</u>, <u>gow</u>n",
    "diphthongs/phonemes/-aʊ-.m4a",
    "diphthongs/examples/cow, now, brown, wow, gown.m4a",
  ],
];

export const consonants = [
  [
    "/p/",
    "p, pp",
    "<u>p</u>en, u<u>pp</u>er, pu<u>pp</u>y, gra<u>p</u>e, ha<u>pp</u>y",
    "consonants/phonemes/-p-.m4a",
    "consonants/examples/pen, upper, puppy, grape, happy.m4a",
  ],
  [
    "/b/",
    "b, bb",
    "<u>b</u>ig, ho<u>bb</u>y, <u>b</u>ee, li<u>b</u>rary, ca<u>b</u>",
    "consonants/phonemes/-b-.m4a",
    "consonants/examples/big, hobby, bee, library, cab.m4a",
  ],
  [
    "/t/",
    "t, tt, bt, ght, ed",
    "<u>t</u>est, ki<u>tt</u>en, dou<u>bt</u>, l<u>ight</u>, work<u>ed</u>",
    "consonants/phonemes/-t-.m4a",
    "consonants/examples/test, kitten, doubt, light, worked.m4a",
  ],
  [
    "/d/",
    "d, dd, de, ld",
    "<u>d</u>aughter, a<u>dd</u>, br<u>ide</u>, wou<u>ld</u>, be<u>d</u>",
    "consonants/phonemes/-d-.m4a",
    "consonants/examples/daughter, add, bride, would, bed.m4a",
  ],
  [
    "/tʃ/",
    "ch, c,  tch, t+ure, t+ion",
    "<u>ch</u>urch, <u>c</u>ello, bea<u>ch</u>, ma<u>ture</u>, ques<u>tion</u>",
    "consonants/phonemes/-tʃ-.m4a",
    "consonants/examples/church, cello, beach, mature, question.m4a",
  ],
  [
    "/dʒ/",
    "g, j, ge, dge, gg",
    "ca<u>ge</u>, <u>j</u>am,  ju<u>dge</u>, su<u>gg</u>est,  e<u>dge</u>",
    "consonants/phonemes/-dʒ-.m4a",
    "consonants/examples/cage, jam, judge, suggest, edge.m4a",
  ],
  [
    "/k/",
    "c, k,  ck, ch, que, q, cc",
    "<u>c</u>ause, <u>k</u>ing,  la<u>ck</u>,  a<u>ch</u>e, <u>que</u>st",
    "consonants/phonemes/-k-.m4a",
    "consonants/examples/cause, king, lack, ache, quest.m4a",
  ],
  [
    "/g/",
    "g, gg, gu, gue, gh",
    "hug, bi<u>gg</u>er, <u>gue</u>st, <u>gh</u>ost, va<u>gue</u>",
    "consonants/phonemes/-g-.m4a",
    "consonants/examples/hug, bigger, guest, ghost, vague.m4a",
  ],
  [
    "/f/",
    "f, ff, ph, lf, fe",
    "<u>f</u>lower, o<u>ff</u>er, gra<u>ph</u>, ha<u>lf</u>, gira<u>ffe</u>",
    "consonants/phonemes/-f-.m4a",
    "consonants/examples/flower, offer, graph, half, giraffe.m4a",
  ],
  [
    "/v/",
    "v, ve",
    "<u>ve</u>st, ha<u>ve</u>, glo<u>ve</u>, wi<u>ve</u>s, wa<u>ve</u>",
    "consonants/phonemes/-v-.m4a",
    "consonants/examples/vest, have, glove, wives, wave.m4a",
  ],
  [
    "/θ/",
    "th",
    "<u>Th</u>ursday, <u>th</u>ank, ba<u>th</u>, no<u>th</u>ing, bo<u>th</u>",
    "consonants/phonemes/-θ-.m4a",
    "consonants/examples/Thursday, thank, bath, nothing, both.m4a",
  ],
  [
    "/ð/",
    "th, the",
    "wi<u>th</u>, mo<u>th</u>er, <u>th</u>ose, ga<u>th</u>er, furt<u>h</u>er",
    "consonants/phonemes/-ð-.m4a",
    "consonants/examples/with, mother, those, gather, further.m4a",
  ],
  [
    "/s/",
    "s, ss,  ps, c, sc, ce, se",
    "ki<u>ss</u>, <u>ps</u>ychology, ri<u>ce</u>, <u>c</u>ircle, pea<u>ce</u>",
    "consonants/phonemes/-s-.m4a",
    "consonants/examples/kiss, psychology, rice, circle, peace.m4a",
  ],
  [
    "/z/",
    "z, zz, se, ss",
    "<u>z</u>oo, ja<u>zz</u>, sci<u>ss</u>or, la<u>z</u>y, qui<u>zz</u>es",
    "consonants/phonemes/-z-.m4a",
    "consonants/examples/zoo, jazz, scissor, lazy, quizzes.m4a",
  ],
  [
    "/ʃ/",
    "sh, ti, ss, ch, tion, sion",
    "<u>sh</u>are, mo<u>tion</u>, pa<u>ssion</u>, ten<u>sion</u>, Engli<u>sh</u>",
    "consonants/phonemes/-ʃ-.m4a",
    "consonants/examples/share, motion, passion, tension, English.m4a",
  ],
  [
    "/ʒ/",
    "s, ge, sion, sure",
    "A<u>si</u>a, ca<u>s</u>ual, bei<u>ge</u>, vi<u>sion</u>, mea<u>sure</u>",
    "consonants/phonemes/-ʒ-.m4a",
    "consonants/examples/Asia, casual, beige, vision, measure.m4a",
  ],
  [
    "/m/",
    "m, mm, mb, me, mn",
    "mom, grammar, climb, game, autumn",
    "consonants/phonemes/m.m4a", // TODO: rename?
    "consonants/examples/mom, grammar, climb, game, autumn.m4a",
  ],
  [
    "/n/",
    "n, ne, nn, kn, pn, gn",
    "nine, connect, knife, pneumonia, gnaw",
    "consonants/phonemes/-n-.m4a",
    "consonants/examples/nine, connect, knife, pneumonia, gnaw.m4a",
  ],
  [
    "/ŋ/",
    "ng, n",
    "sing, bank, angry, drink, jungle",
    "consonants/phonemes/-ŋ-.m4a",
    "consonants/examples/sing, bank, angry, drink, jungle.m4a",
  ],
  [
    "/j/",
    "y, io, u",
    "young, onion, opinion, yes, use",
    "consonants/phonemes/-j-.m4a",
    "consonants/examples/young, onion, opinion, yes, use.m4a",
  ],
  [
    "/l/",
    "l, ll, le",
    "long, pill, table, likely, lamp",
    "consonants/phonemes/-l-.m4a",
    "consonants/examples/long, pill, table, likely, lamp.m4a",
  ],
  [
    "/r/",
    "r, rr, wr, rh",
    "rest, borrow, rhythm, write, wrap",
    "consonants/phonemes/-r-.m4a",
    "consonants/examples/Rest, borrow, rhythm, write, wrap.m4a", // TODO: rename
  ],
  [
    "/w/",
    "w, wh, u, o",
    "west, when, quiet, one, whale",
    "consonants/phonemes/-w-.m4a",
    "consonants/examples/west, when, quiet, one, whale.m4a",
  ],
  [
    "/h/",
    "h, wh",
    "home, whole, who, hair, ahead",
    "consonants/phonemes/-h-.m4a",
    "consonants/examples/home, whole, who, hair, ahead.m4a",
  ],
];

export const vowels = [
  [
    "/iː/",
    "e, ee, ea, ey, ie, y",
    "gr<u>ee</u>n, sh<u>ee</u>p, t<u>ea</u>, k<u>ey</u>, funn<u>y</u>",
    "vowels/phonemes/-iː-.m4a",
    "vowels/examples/green, sheep, tea, key, funny.m4a",
  ],
  [
    "/ɪ/",
    "i, y, ui, u",
    "p<u>i</u>nk, s<u>y</u>mbol, b<u>ui</u>ld, b<u>u</u>sy, q<u>ui</u>lt",
    "vowels/phonemes/-ɪ-.m4a",
    "vowels/examples/-pink, symbol, build, busy, quilt.m4a", // TODO: rename
  ],
  [
    "/ʊ/",
    "oo, ou, u",
    "w<u>oo</u>d, c<u>ou</u>ld, f<u>ul</u>l, b<u>oo</u>k, p<u>u</u>sh",
    "vowels/phonemes/-ʊ-.m4a",
    "vowels/examples/wood, could, full, book, push.m4a",
  ],
  [
    "/uː/",
    "u, o, oo, ou",
    "bl<u>u</u>e, wh<u>o</u>, n<u>oo</u>n, y<u>ou</u>, gr<u>ou</u>p",
    "vowels/phonemes/-uː-.m4a",
    "vowels/examples/blue, who, noon, you, group.m4a",
  ],
  [
    "/e/",
    "e, ea, ai",
    "m<u>e</u>n, br<u>ea</u>d, m<u>e</u>t, s<u>ai</u>d, h<u>ea</u>d",
    "vowels/phonemes/-e-.m4a",
    "vowels/examples/men, bread, met, said, head.m4a",
  ],
  [
    "/ə/",
    "(schwa sound)",
    "b<u>a</u>nana, th<u>e,</u> ev<u>e</u>r, p<u>o</u>lice, <u>u</u>pon",
    "vowels/phonemes/-ə-.m4a",
    "vowels/examples/banana, the, ever, police, upon.m4a",
  ],
  [
    "/ɜː/",
    "i(r), u(r), ea(r)",
    "b<u>ir</u>d, h<u>ur</u>t, l<u>ear</u>n, <u>ear</u>th, f<u>ur</u>niture",
    "vowels/phonemes/-ɜː-.m4a",
    "vowels/examples/bird, hurt, learn, earth, furniture.m4a",
  ],
  [
    "/ɔː/",
    "o(r), oo(r), o(r)e, oa(r)",
    "m<u>or</u>ning, fl<u>oor</u>, w<u>ore</u>, b<u>oar</u>d, sp<u>or</u>t",
    "vowels/phonemes/-ɔː-.m4a",
    "vowels/examples/morning, floor, wore, board, sport.m4a",
  ],
  [
    "/æ/",
    "a, au, ai",
    "<u>a</u>pple, b<u>a</u>ck, pl<u>ai</u>d, l<u>au</u>gh, <u>a</u>fter",
    "vowels/phonemes/-æ-.m4a",
    "vowels/examples/apple, back, plaid, laugh, after.m4a",
  ],
  [
    "/ʌ/",
    "u, o, oo, oe",
    "<u>u</u>nder, h<u>o</u>ney, fl<u>oo</u>d, d<u>oe</u>s, f<u>u</u>n",
    "vowels/phonemes/-ʌ-.m4a",
    "vowels/examples/under, honey, flood, does, fun.m4a",
  ],
  [
    "/aː/",
    "a(r), o, ea(r), ow",
    "h<u>ar</u>d, sh<u>ar</u>k, h<u>ear</u>t, kn<u>ow</u>ledge, b<u>o</u>dy",
    "vowels/phonemes/-aː-.m4a",
    "vowels/examples/hard, shark, heart, knowledge, body.m4a",
  ],
  [
    "/ɒ/",
    "o",
    "l<u>o</u>t, cl<u>o</u>th, h<u>o</u>nest, rob<u>o</u>t, st<u>o</u>p",
    "vowels/phonemes/-ɒ-.m4a",
    "vowels/examples/lot, cloth, honest, robot, stop.m4a",
  ],
];
